services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "vcd"
      POSTGRES_USER: "vcd"
      POSTGRES_PASSWORD: "pgpwd4vcd"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
  runner:
    build: ./RunnerNode
  auth:
    build: ./auth
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: "vcd"
      POSTGRES_USER: "vcd"
      POSTGRES_PASSWORD: "pgpwd4vcd"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
  webserver:
    build: ./UI
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - runner
      - auth