name: Integration / Unit Tests Frontend

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r RunnerNode/requirements.txt

      - name: Install Node.js dependencies
        run: npm ci

      - name: Start FastAPI server in background
        run: |
          uvicorn connect:socket_app --host 0.0.0.0 --port 52525 --reload &
          echo "Waiting for server to start..."
          sleep 5

      - name: Run Jest tests
        run: npm run test