name: Issue closed
on:
  issues:
    types:
      - closed
jobs:
  add_label:
    name: Remove labels
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$ISSUE_ID" --remove-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ISSUE_ID: ${{ github.event.issue.number }}
          LABELS: triage,task

