name: Push workflow
on:
  push
permissions:
  contents: read
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run formatter for UI
        run: |
          npm ci
          npx prettier UI --write
          git add UI
